import { Annotation } from '@langchain/langgraph';
import { CopilotKitStateAnnotation } from '@copilotkit/sdk-js/langgraph';

import { Trip, RideEstimate } from '@repo/shared';
import { RideIntent } from '@/types';
import { RetrievedDocument } from '@/types';

export const RideBookingStateAnnotation = Annotation.Root({
  ...CopilotKitStateAnnotation.spec,

  // Stored estimates for current ride proposal
  rideEstimate: Annotation<RideEstimate | null>({
    reducer: (_, value) => value,
    default: () => null,
  }),

  // Working draft of a trip currently being booked
  tripDraft: Annotation<Partial<Trip> | null>({
    reducer: (state, value) => (value ? { ...state, ...value } : null),
    default: () => null,
  }),

  // User's active and historical trips cached in agent memory
  userTrips: Annotation<Trip[]>({
    reducer: (_, value) => value,
    default: () => [],
  }),

  // Current classified intent
  intent: Annotation<RideIntent | null>({
    reducer: (_, value) => value,
    default: () => null,
  }),

  // Validation errors generated by guardrails
  validationError: Annotation<string | null>({
    reducer: (_, value) => value,
    default: () => null,
  }),

  // Tracks which sub-agent flow is currently active (ride, management, info).
  activeFlow: Annotation<'ride' | 'management' | 'info' | null>({
    reducer: (_, value) => value,
    default: () => null,
  }),

  // Documents retrieved from the knowledge base
  retrievedDocuments: Annotation<RetrievedDocument[]>({
    reducer: (_, value) => value,
    default: () => [],
  }),

  // Current retrieval query (for self-correction tracking)
  retrievalQuery: Annotation<string | null>({
    reducer: (_, value) => value,
    default: () => null,
  }),

  // Whether retrieved docs are relevant (set by retrieval grader)
  retrievalRelevant: Annotation<boolean | null>({
    reducer: (_, value) => value,
    default: () => null,
  }),

  // Retry counter for query rewriting (max 2 retries)
  retrievalRetryCount: Annotation<number>({
    reducer: (_, value) => value,
    default: () => 0,
  }),

  // Result of the cancellation to be displayed via frontend tool
  cancellationResult: Annotation<{
    success: boolean;
    tripId?: string;
    pickup?: string;
    destination?: string;
    cancellationFee?: number;
    reason?: string;
  } | null>({
    reducer: (_, value) => value,
    default: () => null,
  }),
});

export type RideBookingState = typeof RideBookingStateAnnotation.State;
