import { Annotation } from '@langchain/langgraph';
import { CopilotKitStateAnnotation } from '@copilotkit/sdk-js/langgraph';

import { Trip, RideEstimate, RideIntent } from '@/types';

export const RideBookingStateAnnotation = Annotation.Root({
  ...CopilotKitStateAnnotation.spec,

  // Stored estimates for current ride proposal
  rideEstimate: Annotation<RideEstimate | null>({
    reducer: (_, value) => value,
    default: () => null,
  }),

  // Working draft of a trip currently being booked
  tripDraft: Annotation<Partial<Trip> | null>({
    reducer: (state, value) => (value ? { ...state, ...value } : null),
    default: () => null,
  }),

  // User's active and historical trips cached in agent memory
  userTrips: Annotation<Trip[]>({
    reducer: (_, value) => value,
    default: () => [],
  }),

  // Current classified intent
  intent: Annotation<RideIntent | null>({
    reducer: (_, value) => value,
    default: () => null,
  }),

  // Validation errors generated by guardrails
  validationError: Annotation<string | null>({
    reducer: (_, value) => value,
    default: () => null,
  }),
});

export type RideBookingState = typeof RideBookingStateAnnotation.State;
