import { Annotation } from '@langchain/langgraph';
import { CopilotKitStateAnnotation } from '@copilotkit/sdk-js/langgraph';

export type TripStatus = 'searching' | 'matched' | 'picked_up' | 'completed' | 'cancelled';
export type VehicleType = 'bike' | 'car4' | 'car7';

export interface Driver {
  name: string;
  phone: string;
  vehicleInfo: string;
  licensePlate: string;
  rating: number;
}

export interface Trip {
  id: string;
  pickup: string;
  destination: string;
  distance: number;
  duration: number;
  vehicleType: VehicleType;
  passengerName: string;
  passengerPhone: string;
  price: number;
  status: TripStatus;
  driver?: Driver | null;
  createdAt: string;
  cancelledAt?: string;
  cancellationFee?: number;
}

export interface RideEstimate {
  pickup: string;
  destination: string;
  distance: number;
  duration: number;
  options: {
    vehicleType: VehicleType;
    price: number;
  }[];
}

export interface RideIntent {
  category: 'estimate' | 'request' | 'cancel' | 'view_trips' | 'faq' | 'unknown';
  confidence: number;
}

export const RideBookingStateAnnotation = Annotation.Root({
  ...CopilotKitStateAnnotation.spec,

  // Stored estimates for current ride proposal
  rideEstimate: Annotation<RideEstimate | null>({
    reducer: (_, value) => value,
    default: () => null,
  }),

  // Working draft of a trip currently being booked
  tripDraft: Annotation<Partial<Trip> | null>({
    reducer: (state, value) => (value ? { ...state, ...value } : null),
    default: () => null,
  }),

  // User's active and historical trips cached in agent memory
  userTrips: Annotation<Trip[]>({
    reducer: (_, value) => value,
    default: () => [],
  }),

  // Current classified intent
  intent: Annotation<RideIntent | null>({
    reducer: (_, value) => value,
    default: () => null,
  }),

  // Validation errors generated by guardrails
  validationError: Annotation<string | null>({
    reducer: (_, value) => value,
    default: () => null,
  }),
});

export type RideBookingState = typeof RideBookingStateAnnotation.State;
