export const BUSINESS_RULES = {
  MAX_RIDE_DISTANCE_KM: 50,
  MAX_ACTIVE_TRIPS: 3,
  OPERATING_HOURS: {
    START: 5,
    END: 23,
  },
  AVERAGE_SPEED_KMH: 30,
  FALLBACK_ESTIMATE: {
    DISTANCE_MULTIPLIER: 1.3,
    DURATION_MULTIPLIER: 1.5,
    DURATION_OFFSET: 5,
  },
};
