import { AIMessage } from '@langchain/core/messages';
import { RideBookingState } from '../state/state';

/**
 * Route After Chat
 *
 * Inspects the last message generated by the agent. If the agent
 * made a tool call (that is NOT a CopilotKit frontend action),
 * routes to 'tool_node'. Otherwise, ends the execution turn.
 */
export function routeAfterChat(state: RideBookingState) {
  const messages = state.messages || [];
  const lastMessage = messages[messages.length - 1] as AIMessage;

  if (lastMessage && lastMessage.tool_calls?.length) {
    const actions = state.copilotkit?.actions;
    const toolCallName = lastMessage.tool_calls[0].name;

    // If it's a frontend action, CopilotKit will execute it on the client side.
    // We only route to tool_node if it's a backend tool.
    if (!actions || actions.every((action) => action.name !== toolCallName)) {
      return 'tool_node';
    }
  }

  return '__end__';
}
